### ISSUE TITLE
Implementar equals() y hashCode() en modelos

### ISSUE THREAD

**Issue by Hecta18** [R-0WL/Proyecto-Turismo#2]
Estas funciones, que van sobreescritas, ayudan a garantizar la integridad de los datos en estructuras de datos. HashCode devuelve un hash(numero) que identifica un dato y equals compara datos. Si 2 objetos son considerados iguales por equals(), deben devolver el mismo valor de hashCode().

**Comment by LemCar247** [comment]
hola

**Comment by Hecta18** [comment]
Alguien le sabe a esto?

**Comment by LemCar247** [comment]
Yo puse algo ahi, pero no estoy seguro si realmente sirve

**Comment by Hecta18** [comment]
Quedo chingon. Solo ahorita ya investigue bien y solo es para cuando la info se guarda en alguna estructura que usa hashes. Hay q ver que dice Rene, pero creo q la BDs no usa... :"v

**Comment by Hecta18** [comment]
Rene confirmo q es una muy buena practica de seguridad guardar los datos como codigos hash en la base de datos. Asi q ya esta implementado y listo para usarse!!!
